// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkQWe-D-__v9GiwhYKXds2JJMFp4wyG9M',
    appId: '1:595805505802:web:3a39ce111c41f0191152f3',
    messagingSenderId: '595805505802',
    projectId: 'mynotes-pdimitrios',
    authDomain: 'mynotes-pdimitrios.firebaseapp.com',
    storageBucket: 'mynotes-pdimitrios.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL25VXaLL4xz7FY4HQ2U0ozIN60TSgXS0',
    appId: '1:595805505802:android:756c0832f59557031152f3',
    messagingSenderId: '595805505802',
    projectId: 'mynotes-pdimitrios',
    storageBucket: 'mynotes-pdimitrios.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeISF6EumFsPft6DktO-wJhG37vGGgC_w',
    appId: '1:595805505802:ios:97fa614b4652c8e31152f3',
    messagingSenderId: '595805505802',
    projectId: 'mynotes-pdimitrios',
    storageBucket: 'mynotes-pdimitrios.appspot.com',
    iosClientId: '595805505802-sf4qhmd8d94jq3tnt4k8104f05jsbqj8.apps.googleusercontent.com',
    iosBundleId: 'com.mitsaras.dimitrisNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeISF6EumFsPft6DktO-wJhG37vGGgC_w',
    appId: '1:595805505802:ios:97fa614b4652c8e31152f3',
    messagingSenderId: '595805505802',
    projectId: 'mynotes-pdimitrios',
    storageBucket: 'mynotes-pdimitrios.appspot.com',
    iosClientId: '595805505802-sf4qhmd8d94jq3tnt4k8104f05jsbqj8.apps.googleusercontent.com',
    iosBundleId: 'com.mitsaras.dimitrisNotes',
  );
}
